### ISSUE TITLE
Print support

### ISSUE THREAD

**Issue by mdevan** [apankrat/nullboard#4]
The following makes the print / print preview appear better:

```css
@media print {
    .teaser, .logo {
        visibility: hidden;
    }
}
```

Would be great if you could add in something like this.
